### ISSUE TITLE
Implement spectral subsamping in conversion to isetbio display object

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/BLIlluminationDiscriminationCalcs#1]
Brainard lab calibrations are typically at 2 nm sampling intervals.  This is very fine relative to what we probably need when the end goal is to compute cone isomerization rates, and preserving 2 nm sampling leads to very slow calculations with hyperspectal images. 

Implement a smoothing and subsampling option at the stage where we produce an isetbio display object from a Brainard lab calibration structure.

Do this by passing an S vector.  An S vector is of form ([start delta n] where start is the starting wavelength in nm, delta is the wavelength spacing, and n is the number of spectral samples.  So 380 to 780 in 2 nm steps is [380 2 201], while 400 to 700 in 10 nm steps is [400 10 31].  Using [400 10 31] is probably good.

The function SplineSpd will convert from one S to another.  Probably we want to implement a smoothing step before calling this, and validate that the cone responses to the monitor primaries do not change too much with the subsampling we choose.

Note also that the Brainard lab data specify power per wavelength sample while isetbio wants power per nm.  So one needs to divide the Brainard lab spectra data by the wavelength sampling size somewhere in the conversion process.

**Comment by npcottaris** [comment]
This is now implemented via the new function **_subSampleSPDs**_, whose syntax is:

```
[subSampledWavelengthSampling, subSampledSPDs] = subSampleSPDs( ...
       originalS, originalSPDs, ...
       newSamplingIntervalInNanometers, lowPassSigmaInNanometers, ...
       maintainTotalEnergy, showFig);
```

For more information:

```
 doc subSampleSPDs
```

**Comment by npcottaris** [comment]
Subsampling with a sampling interval of 8 nm, I obtained the following speed ups:
- Scene object generation:               **1.4** seconds vs  **5.5** seconds with original spds
- Optical image object generation: **11.6** seconds vs **46.2** seconds with original spds

so a factor of around 4, as was expected.

**Comment by xnieamo** [comment]
The function that converts the calibration files to isetbio format now takes in an optional S sector
