### ISSUE TITLE
Make ancillary data used in cal conversion more transparent.  

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/BLIlluminationDiscriminationCalcs#2]
We don't routinely specify distance to screen in our calibration files.  So this info needs to be added as our cal files are converted to isetbio display objects.  Make this an argument to the conversion routine, so that the caller must specify it explicitly.  Actually, perhaps the argument should be a required struct, which at the moment has one required field which is the distance.  This would let us add other fields in the future without having to change the arguments passed.

**Comment by xnieamo** [comment]
I've added a class called ExtraCalData that currently only has distance as a field.  The conversion function has been updated to require this struct as an input.
